version: "3.9"

services:
    server:
        build:
            context: "."
            dockerfile: "server/Dockerfile"
        networks:
            - my_network
        environment:
            - LISTEN_PORT=${BACKEND_PORT}
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        env_file:
            - .env

    proxy:
        build: "./proxy"
        depends_on:
            - server
        networks:
            - my_network
        environment:
            - ADMIN_PORT=${PROXY_ADMIN_PORT}
            - LISTEN_PORT=${PROXY_LISTEN_PORT}
            - BACKEND_IP=server
            - BACKEND_PORT=${BACKEND_PORT}
        ports:
            - "${PROXY_ADMIN_PORT}:${PROXY_ADMIN_PORT}"
            - "${PROXY_LISTEN_PORT}:${PROXY_LISTEN_PORT}"
        env_file:
            - .env

networks:
    my_network:
