version: "3.9"

services:
    server:
        build:
            context: "."
            dockerfile: "server/Dockerfile"
        networks:
            - my_network
        ports:
            - "10000:10000"

    proxy:
        build: "./proxy"
        depends_on:
            - server
        networks:
            - my_network
        ports:
            - "80:80"
            - "8080:8080"

networks:
    my_network:
